// The service worker: what makes Vibe open on an iPad with no signal.
//
// Deliberately small, and deliberately hand-written rather than generated by
// Workbox. Two reasons. The only genuinely awkward part of a precache is
// knowing the hashed asset filenames, and a fifteen-line Vite plugin
// (`serviceWorker()` in vite.config.js) supplies those — everything else here
// is a policy decision that should be readable in one screen. And this app
// keeps a short dependency list on purpose; workbox-build and workbox-window
// would be three new ones to make a file this size.
//
// A service worker sits in front of every request from every user, so the
// rules below are conservative by design:
//
//   - NOTHING FROM /api OR /fmi IS EVER CACHED. Those carry records, sessions
//     and someone's identity. A stale record served from a cache would look
//     exactly like a record that failed to save, and a cached /api/me would be
//     one person's session handed to whoever opened the app next. The offline
//     copy of a record lives in IndexedDB, written deliberately by "Take
//     offline" — never as a side effect of a fetch passing through here.
//   - ONLY GET IS TOUCHED. A POST is a write; it either reaches the server or
//     it is queued by the app, and this file has no opinion either way.
//   - THE APP SHELL IS PRECACHED, and it is content-hashed, so a cached asset
//     can never be the wrong version of itself.
//
// If this ever needs to be switched off in a hurry, ship a `src/sw.js` whose
// only body is `self.registration.unregister()`; the update path below picks it
// up on the next load and every client drops back to the network.

const VERSION = __SW_VERSION__;
const SHELL = `vibe-shell-${VERSION}`;
const FONTS = 'vibe-fonts-v1';

// Injected at build time from the real output filenames.
const PRECACHE = __PRECACHE__;

// The API and the FileMaker proxy. Never cached, in either direction.
const NEVER = [/^\/api\//, /^\/fmi\//, /^\/Streaming_SSL\//, /^\/fmws\//, /^\/oauth\//];

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    // `reload` so a precache never picks the browser's own stale HTTP copy —
    // which is how a "cleared cache, still broken" afternoon starts.
    await cache.addAll(PRECACHE.map(u => new Request(u, { cache: 'reload' })));
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keep = new Set([SHELL, FONTS]);
    await Promise.all((await caches.keys()).map(k => (keep.has(k) ? null : caches.delete(k))));
    // NOT `clients.claim()`. Claiming would put a freshly installed worker in
    // charge of a page whose JavaScript came from the previous build — a
    // mismatch that shows up as one broken screen rather than an error. Pages
    // pick this worker up on their next load instead.
  })());
});

// The page decides WHEN a waiting worker takes over (see src/registerSW.js).
// Once there is an outbox, that decision has to consider unsynced work, and a
// worker that called skipWaiting() on its own would have taken it already.
self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

const isNever = path => NEVER.some(re => re.test(path));

// Google Fonts. Worth the special case: without it the app loses Source Sans
// and Oswald the moment it is offline, and every screen reflows into a system
// font — which reads as "the app is broken" rather than "the network is gone".
const isFont = url =>
  url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com';

async function staleWhileRevalidate(cacheName, request) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  const network = fetch(request)
    .then(res => { if (res.ok) cache.put(request, res.clone()); return res; })
    .catch(() => null);
  return hit || (await network) || Response.error();
}

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  if (isFont(url)) { event.respondWith(staleWhileRevalidate(FONTS, request)); return; }

  // Anything else off-origin is left entirely alone.
  if (url.origin !== self.location.origin) return;
  if (isNever(url.pathname)) return;

  // A navigation is answered from the precached shell. The app is hash-routed,
  // so every route is the same document, and serving it from the cache is what
  // lets the app open in a field with no signal at all.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cached = await caches.match('/index.html', { cacheName: SHELL });
      if (cached) return cached;
      try { return await fetch(request); }
      catch { return new Response('Offline, and the app shell was never cached.', { status: 503 }); }
    })());
    return;
  }

  // Hashed build assets: cache-first, because the name IS the version.
  event.respondWith((async () => {
    const cached = await caches.match(request, { cacheName: SHELL });
    if (cached) return cached;
    try {
      const res = await fetch(request);
      if (res.ok && res.type === 'basic') {
        const cache = await caches.open(SHELL);
        cache.put(request, res.clone());
      }
      return res;
    } catch (e) {
      const fallback = await caches.match(request);
      if (fallback) return fallback;
      throw e;
    }
  })());
});
