"""Derive palette.json from brand.json.

    python tokens/derive_palette.py

WHY THIS SCRIPT EXISTS AT ALL.

The system this is modelled on samples its palette from a published design-system
file: 9 hues x 12 gradations, already drawn, never hand-edited. High 5's style sheet
publishes SEVEN FLAT COLOURS AND NO RAMPS. A UI needs tints for surfaces and shades
for text, so the ramps have to come from somewhere, and the honest options were to
invent them by eye or to derive them reproducibly. This does the second.

So the provenance splits cleanly, and the split is the point:

    brand.json   the seven colours, verbatim from the style sheet.  BRAND STANDARD.
    palette.json the ramps around them, generated by this script.   HOUSE CONVENTION.

Every anchor appears UNCHANGED at its own step, so no brand colour is ever altered by
the derivation — only surrounded. `tests/test_palette.py` asserts that.

HOW THE RAMP IS BUILT.

Interpolation happens in CIELAB, not sRGB. Mixing a hex toward white in sRGB darkens
and dulls the mid-tones — the classic muddy ramp — because sRGB is not perceptually
uniform. LAB is close enough to uniform that an even spread of L* reads as an even
spread of lightness.

Target L* per step is calibrated against the source system's own curve, which is
consistent across all of its hues:

    0:100  100:97  200:95  300:93  400:88  500:78  600:57  700:47  800:35  900:27
    1000:13  1100:0

Chroma tapers toward both ends. A tint at L*97 with the anchor's full chroma is a
garish pastel, and a shade at L*13 with it is indistinguishable from black; easing
chroma down as lightness approaches either extreme is what keeps the pale steps
recognisably the brand hue and the dark steps from collapsing into each other.
"""

import collections
import json
import os
from pathlib import Path

os.chdir(Path(__file__).resolve().parent.parent)

BRAND = json.loads(Path("brand.json").read_text())

# Calibrated against the source system's measured curve (see module docstring).
GRADATIONS = collections.OrderedDict(
    [
        (0, 100.0),
        (100, 97.0),
        (200, 95.0),
        (300, 93.0),
        (400, 88.0),
        (500, 78.0),
        (600, 57.0),
        (700, 47.0),
        (800, 35.0),
        (900, 27.0),
        (1000, 13.0),
        (1100, 0.0),
    ]
)

# Steps a component may consume. The rest exist for data/category encoding and for
# the generator's own use, and BRAND.md says so. Mirrors the source system's
# core/extended split, which exists to stop a palette of 96 values becoming 96
# equally-reachable choices.
CORE_STEPS = {100, 200, 300, 400, 600, 700, 800, 1000}


# ---------------------------------------------------------------------------
# Colour maths. Stdlib only, deliberately: this tree must be runnable by anyone
# who has checked the repo out, with no install step, or it will not be run.
# ---------------------------------------------------------------------------

def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i : i + 2], 16) / 255 for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return "#" + "".join(f"{max(0, min(255, round(c * 255))):02X}" for c in rgb)


def _srgb_to_linear(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _linear_to_srgb(c):
    c = max(0.0, min(1.0, c))
    return c * 12.92 if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055


# D65 white point.
_WX, _WY, _WZ = 0.95047, 1.00000, 1.08883


def rgb_to_lab(rgb):
    r, g, b = (_srgb_to_linear(c) for c in rgb)
    x = (0.4124564 * r + 0.3575761 * g + 0.1804375 * b) / _WX
    y = (0.2126729 * r + 0.7151522 * g + 0.0721750 * b) / _WY
    z = (0.0193339 * r + 0.1191920 * g + 0.9503041 * b) / _WZ

    def f(t):
        return t ** (1 / 3) if t > 0.008856 else (903.3 * t + 16) / 116

    fx, fy, fz = f(x), f(y), f(z)
    return (116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz))


def lab_to_rgb(lab):
    L, a, b = lab
    fy = (L + 16) / 116
    fx, fz = fy + a / 500, fy - b / 200

    def inv(t):
        return t ** 3 if t ** 3 > 0.008856 else (116 * t - 16) / 903.3

    x, y, z = inv(fx) * _WX, inv(fy) * _WY, inv(fz) * _WZ
    r = 3.2404542 * x - 1.5371385 * y - 0.4985314 * z
    g = -0.9692660 * x + 1.8760108 * y + 0.0415560 * z
    bb = 0.0556434 * x - 0.2040259 * y + 1.0572252 * z
    return tuple(_linear_to_srgb(c) for c in (r, g, bb))


def relative_luminance(hex_colour):
    r, g, b = (_srgb_to_linear(c) for c in hex_to_rgb(hex_colour))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast_ratio(a, b):
    la, lb = relative_luminance(a), relative_luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


# ---------------------------------------------------------------------------

def chroma_scale(target_L, anchor_L):
    """How much of the anchor's chroma survives at a given lightness.

    Full chroma at the anchor, easing off toward both ends. Without this the pale
    steps come out as fluorescent pastels and the dark steps all converge on the
    same near-black, which defeats the purpose of having twelve of them.
    """
    if target_L >= 99.5:
        return 0.0  # step 0 is white; a tinted "white" is not a surface colour
    if target_L <= 0.5:
        return 0.0  # step 1100 is black
    if target_L > anchor_L:
        # Lighter than the anchor: fade toward white.
        span = 100.0 - anchor_L
        return 1.0 - 0.72 * ((target_L - anchor_L) / span if span else 0)
    # Darker than the anchor: hold more chroma, since a dark tone loses its identity
    # faster than a light one.
    span = anchor_L
    return 1.0 - 0.45 * ((anchor_L - target_L) / span if span else 0)


def ramp(anchor_hex):
    """Twelve steps around one anchor colour.

    The step whose target L* is closest to the anchor's own is replaced by the anchor
    EXACTLY — the brand colour is never approximated by its own ramp.
    """
    L0, a0, b0 = rgb_to_lab(hex_to_rgb(anchor_hex))
    anchor_step = min(GRADATIONS, key=lambda s: abs(GRADATIONS[s] - L0))

    out = collections.OrderedDict()
    for step, target_L in GRADATIONS.items():
        if step == anchor_step:
            out[step] = {"hex": anchor_hex.upper(), "anchor": True}
            continue
        k = chroma_scale(target_L, L0)
        hexv = rgb_to_hex(lab_to_rgb((target_L, a0 * k, b0 * k)))
        out[step] = {"hex": hexv, "anchor": False}
    return out, anchor_step


def build():
    hues = collections.OrderedDict()
    anchors = {}

    # Grey first, so it reads first in the file — it is the one every surface and
    # every piece of body text depends on.
    grey_ramp, grey_anchor = ramp(BRAND["colors"]["black"]["hex"])
    # Pure black has zero chroma, so its ramp is a true neutral. Stated rather than
    # assumed: a "grey" derived from a tinted black would cast every surface.
    hues["grey"] = grey_ramp
    anchors["grey"] = grey_anchor

    for name in ["red", "gold", "blue", "mustard", "khaki", "purple"]:
        r, anchor_step = ramp(BRAND["colors"][name]["hex"])
        hues[name] = r
        anchors[name] = anchor_step

    green_ramp, green_anchor = ramp(BRAND["derived_hues"]["green"]["hex"])
    hues["green"] = green_ramp
    anchors["green"] = green_anchor

    # Tier every step, and record the anchor, so consumers can tell a brand value
    # from a derived one without consulting a document.
    for hue, steps in hues.items():
        for step, d in steps.items():
            d["tier"] = "core" if step in CORE_STEPS else "extended"
            d["contrast_on_white"] = round(contrast_ratio(d["hex"], "#FFFFFF"), 2)
            d["contrast_on_black"] = round(contrast_ratio(d["hex"], "#000000"), 2)

    palette = collections.OrderedDict()
    palette["$schema_note"] = (
        "DERIVED — do not hand-edit. Generated by tokens/derive_palette.py from "
        "brand.json, which is the source of truth. Each hue is twelve gradations "
        'around one anchor; the step marked "anchor": true is the brand colour '
        "itself, unchanged. Every other value is a house convention, because the "
        "High 5 style sheet publishes no gradations. tier=core is the subset a "
        "component may consume; tier=extended is for data and category encoding."
    )
    palette["source"] = {
        "brand_file": "brand.json",
        "brand_source": BRAND["source"]["name"],
        "generator": "tokens/derive_palette.py",
        "method": (
            "CIELAB interpolation to a fixed L* curve, chroma tapered toward both "
            "ends. sRGB interpolation was rejected: it darkens and dulls mid-tones "
            "because sRGB is not perceptually uniform."
        ),
    }
    palette["gradations"] = list(GRADATIONS.keys())
    palette["anchors"] = anchors
    palette["hues"] = hues
    return palette


if __name__ == "__main__":
    p = build()
    Path("palette.json").write_text(json.dumps(p, indent=2) + "\n")
    n = sum(len(v) for v in p["hues"].values())
    print(f"palette.json: {len(p['hues'])} hues x {len(p['gradations'])} gradations = {n} values")
    for hue, step in p["anchors"].items():
        print(f"  {hue:<8} anchor at step {step:<5} {p['hues'][hue][step]['hex']}")
